server:
  port: 8099
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/company_info}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update





